#!/bin/sh
set -efu

pythons="$(py3versions -s 2> /dev/null)"

cp -a docs tests.py "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for python in $pythons; do
	echo "=== $python ==="
	$python tests.py 2>&1
done
